get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/ap_idle -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/ap_int_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/ap_ext_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/ap_str_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_default_function_fu_334/ap_idle -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_default_function_fu_334/ap_int_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_default_function_fu_334/ap_ext_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_default_function_fu_334/ap_str_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_knn_vote_fu_341/ap_idle -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_knn_vote_fu_341/ap_int_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_knn_vote_fu_341/ap_ext_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/DigitRec_1/inst/grp_knn_vote_fu_341/ap_str_blocking_n -time 0 -quiet
get_value_database /emu_wrapper/emu_i/xilmonitor_DigitRec_1_m_axi_gmem/inst/readActive -time 0 -quiet
get_value_database /emu_wrapper/emu_i/xilmonitor_DigitRec_1_m_axi_gmem/inst/writeActive -time 0 -quiet
