#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2_AR71275_op (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Oct 04 21:25:02 UTC 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -prj emu_wrapper_vlog.prj"
ExecStep xvlog --incr --relax -prj emu_wrapper_vlog.prj 2>&1 | tee compile.log
echo "xvhdl --incr --relax -prj emu_wrapper_vhdl.prj"
ExecStep xvhdl --incr --relax -prj emu_wrapper_vhdl.prj 2>&1 | tee -a compile.log

echo "xsc -c --gcc_compile_options "-I/opt/Xilinx/Vivado/2018.2.op2258646/data/simmodels/xsim/2018.2/lnx64/6.2.0/ext/protobuf/include" --gcc_compile_options "-I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/ddrx_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/axi_crossbar_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/top -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/xdma_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/ddrx_v3/cpp_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/common -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/xdma_v3/cpp_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon2_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon2_0_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_accel_mon_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_accel_mon_0_0/sim" -work xil_defaultlib -f emu_wrapper_xsc.prj"
ExecStep xsc -c --gcc_compile_options "-I/opt/Xilinx/Vivado/2018.2.op2258646/data/simmodels/xsim/2018.2/lnx64/6.2.0/ext/protobuf/include" --gcc_compile_options "-I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/ddrx_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/axi_crossbar_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/top -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/xdma_v3/systemc_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/ddrx_v3/cpp_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/common -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm/xdma_v3/cpp_srcs -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon2_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_axi_perf_mon2_0_0/sim -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_accel_mon_0_0/sysc -I../../../../prj.srcs/sources_1/bd/emu/ip/emu_sim_accel_mon_0_0/sim" -work xil_defaultlib -f emu_wrapper_xsc.prj 2>&1 | tee -a compile.log
