#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2_AR71275_op (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 04 21:25:02 UTC 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
xv_lib_path="/opt/Xilinx/Vivado/2018.2.op2258646/patches/AR71275/vivado/lib/lnx64.o/Default:/opt/Xilinx/Vivado/2018.2.op2258646/patches/AR71275/vivado/lib/lnx64.o:/opt/Xilinx/Vivado/2018.2.op2258646/lib/lnx64.o/Default:/opt/Xilinx/Vivado/2018.2.op2258646/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$LD_LIBRARY_PATH

xv_lib_path="/opt/Xilinx/Vivado/2018.2.op2258646/patches/AR71275/vivado/lib/lnx64.o/Default:/opt/Xilinx/Vivado/2018.2.op2258646/patches/AR71275/vivado/lib/lnx64.o:/opt/Xilinx/Vivado/2018.2.op2258646/lib/lnx64.o/Default:/opt/Xilinx/Vivado/2018.2.op2258646/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$LD_LIBRARY_PATH

ExecStep ./xsim.dir/emu_wrapper_behav/axsim $*
